### ISSUE TITLE
PJON Linux serial support

### ISSUE THREAD

**Issue by gioblu** [xlfe/PJON-cython#1]
Ciao @xlfe compliments for the development done on PJON-cython, its new release and the LINUX serial support. Would you open a pull-request to the PJON repo to add the LINUX serial support?
Keep up the good work and thank you again for your support.

**Comment by xlfe** [comment]
Hi @gioblu thanks - of course happy to submit a pull request - but I thought you wanted a broader rewrite (as per the discussion here https://github.com/gioblu/PJON/issues/232)? 

- at the moment the only difference between gioblu/PJON and xlfe/PJON is

Linux Serial support using WiringPi
https://github.com/gioblu/PJON/commit/a3ef89eed88f659376cfa6ccc60a32bd3b470516
and @fredilarsen pull request for GlobalUDP auto-registration
https://github.com/gioblu/PJON/pull/235

**Comment by gioblu** [comment]
Ciao @xlfe thank you for your fast reply, I have answered you here (https://github.com/gioblu/PJON/issues/232)

I will accept auto-registration as soon as possible.

**Comment by xlfe** [comment]
Ah great - thanks for clarifying. I will send a pull request in the next
few hours

**Comment by gioblu** [comment]
Thank you very much @xlfe 
I would have accepted earlier the auto-registration support, but it contains some changes that may break some edge cases so I need a complete round of testing (of all supported devices).
