### ISSUE TITLE
python setup.py install  failed with error D8021

### ISSUE THREAD

**Issue by suprimex** [xlfe/PJON-cython#3]
In short: 
cl : Command line error D8021 : invalid numeric argument '/Wno-unneeded-internal-declaration'

Platform: Win10 x64, Python 2.7.14

Full output:
f:\compile\PJON-cython>python setup.py install
running install
running bdist_egg
running egg_info
creating pjon_cython.egg-info
writing pjon_cython.egg-info\PKG-INFO
writing top-level names to pjon_cython.egg-info\top_level.txt
writing dependency_links to pjon_cython.egg-info\dependency_links.txt
writing manifest file 'pjon_cython.egg-info\SOURCES.txt'
package init file 'pjon_cython\__init__.py' not found (or not a regular file)
reading manifest file 'pjon_cython.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pjon_cython.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'pjon_cython' extension
creating build
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\pjon_cython
C:\Users\<username>\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IPJON/src -IC:\Python27\x64\include -IC:\Python27\x64\PC /Tppjon_cython/pjon_cython.cpp /Fobuild\temp.win-amd64-2.7\Release\pjon_cython/pjon_cython.obj -std=c++11 -DLINUX -std=c++11 -DLINUX -DPJON_INCLUDE_TS -DPJON_INCLUDE_LUDP -DPJON_INCLUDE_GUDP -Wno-unneeded-internal-declaration -Wno-unused-variable
cl : Command line error D8021 : invalid numeric argument '/Wno-unneeded-internal-declaration'
error: command 'C:\\Users\\<username>\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by xlfe** [comment]
@suprimex thanks for the bug report - 

Hopefully this is easy to fix.

Can you try pulling the latest master branch, changing setup.py and then running "setup.py install" again

```python
                  extra_compile_args=[
                        '-std=c++11',
                        '-DPJON_INCLUDE_TS',
                        '-DPJON_INCLUDE_LUDP',
                        '-DPJON_INCLUDE_GUDP',
                        # '-DPJON_INCLUDE_PACKET_ID=true',
                        # '-DPJON_INCLUDE_ASYNC_ACK=true',
                        '-DLINUX',
                        '-Wno-unneeded-internal-declaration',
                        '-Wno-unused-variable'],
 ```

to
```python
                  extra_compile_args=[
                        '-std=c++11',
                        '-DPJON_INCLUDE_TS',
                        '-DPJON_INCLUDE_LUDP',
                        '-DPJON_INCLUDE_GUDP',
                        '-DWINX86'],
 ```

I don't have access to a windows machine yet to test, but I'll set one up shortly

**Comment by suprimex** [comment]
Now it stopped with dependencies:
f:\compile\pjon-cython\pjon\src\interfaces\WINX86/PJON_WINX86_Interface.h(23) : fatal error C1083: Cannot open include file: 'chrono': No such file or directory

But as I can understand, Microsoft Visual C++ for Python 9.0 doesn't include this file.

**Comment by xlfe** [comment]
@suprimex - yes sorry it looks like it might be the version of visual studio as you say?

http://www.cplusplus.com/forum/general/108928/

I'm not sure actually if I will be able to include formal windows support unfortunately.
