### ISSUE TITLE
Internal inclusion change in PJON

### ISSUE THREAD

**Issue by gioblu** [xlfe/PJON-cython#6]
Ciao @xlfe thank you very much for PJON-cython 👍 
I have changed in PJON the inclusion of internal sources chaging from `<>` to `""`: https://github.com/gioblu/PJON/commit/6fcfd759c6f376bd1328a681bd644790fea021b2
This was required to ease the integration with MySensors, do this change break something here?

**Comment by xlfe** [comment]
Hi @gioblu 

no problems building or tests with the current sources

[log-73dd183e-5cd2-44aa-8974-e3b7e1470910.txt](https://github.com/xlfe/PJON-cython/files/2594726/log-73dd183e-5cd2-44aa-8974-e3b7e1470910.txt)
