### ISSUE TITLE
PJON v12.0 support

### ISSUE THREAD

**Issue by gioblu** [xlfe/PJON-cython#7]
Ciao @xlfe how its going? 
Do you plan to update PJON-cython to be compatible to the next release?
If so in master you find the code :)

**Comment by xlfe** [comment]
Yes will have a look over the weekend. Thanks for the nudge

**Comment by gioblu** [comment]
@xlfe thank you for your support to the project :)

**Comment by xlfe** [comment]
All tests currently passing

[log-64aab258-3bf0-4e0e-b0bc-5737855bd456.txt](https://github.com/xlfe/PJON-cython/files/3431240/log-64aab258-3bf0-4e0e-b0bc-5737855bd456.txt)

**Comment by gioblu** [comment]
Thank you very much @xlfe and compliments again for PJON-cython I am sure a lot of users will find it useful. Consider to publish on hn/reddit related rooms about your newly released version, that will help to attract users and get more feedback.

**Comment by gioblu** [comment]
I will ping you as soon release will be behind the corner :)
Thank you again.

**Comment by xlfe** [comment]
Updated for PJON 12
Added python 3.7 as officially supported
[log-38e29dcc-a134-4d3a-8caa-413c58864405.txt](https://github.com/xlfe/PJON-cython/files/3781815/log-38e29dcc-a134-4d3a-8caa-413c58864405.txt)

**Comment by xlfe** [comment]
https://pypi.org/project/pjon-cython/12.0.0/

**Comment by xlfe** [comment]
@gioblu updated for PJON v12
